repos:
  - repo: local
    hooks:
      - id: project-check
        name: Project Check
        entry: ./scripts/check.sh
        language: system
        pass_filenames: false
        always_run: true